import React,{useEffect,useMemo,useRef,useState} from "react";
import ReactDOM from "react-dom/client";
import "./styles.css";

const API=(import.meta.env.VITE_API_URL||"http://127.0.0.1:8000").replace(/\/$/,"");
async function request(path,options={},timeoutMs=60000){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeoutMs);try{const r=await fetch(`${API}${path}`,{...options,signal:c.signal});const text=await r.text();let b={};try{b=text?JSON.parse(text):{}}catch{b={detail:text}}if(!r.ok)throw new Error(b.detail||b.message||`Request failed (${r.status})`);return b}catch(e){if(e.name==="AbortError")throw new Error("Analysis timed out. Try a smaller file or check the service.");throw e}finally{clearTimeout(t)}}
const bytes=n=>!Number.isFinite(n)?"—":n<1024?`${n} B`:n<1048576?`${(n/1024).toFixed(1)} KB`:n<1073741824?`${(n/1048576).toFixed(1)} MB`:`${(n/1073741824).toFixed(1)} GB`;
const Icon=({t})=><span className="ico">{{shield:"◈",image:"▧",video:"▶",file:"▤",folder:"⌘",link:"↗",arrow:"→"}[t]||"•"}</span>;

function App(){
 const [mode,setMode]=useState("image"),[files,setFiles]=useState([]),[url,setUrl]=useState(""),[result,setResult]=useState(null),[batch,setBatch]=useState([]),[audit,setAudit]=useState(null),[health,setHealth]=useState(null),[loading,setLoading]=useState(false),[progress,setProgress]=useState(0),[error,setError]=useState(""),[notice,setNotice]=useState(""),[tab,setTab]=useState("scanner");
 const input=useRef(null);
 const risk=useMemo(()=>{const r=result?.analysis?.risk||result||{};return{score:Math.max(0,Math.min(100,Math.round(Number(r.risk_score??0)))),level:r.risk_level||"READY",action:r.recommended_action||"—",confidence:Number(r.confidence??0),factors:r.risk_factors||[]}},[result]);
 const risky=risk.score>=25;
 async function load(){try{const[h,a]=await Promise.all([request("/api/health",{},15000),request("/api/audit/events",{},15000)]);setHealth(h);setAudit(a)}catch{setHealth(null)}}
 useEffect(()=>{load()},[]);
 function clear(){setFiles([]);setResult(null);setBatch([]);setError("");setNotice("");if(input.current)input.current.value=""}
 function selectMode(m){setMode(m);clear()}
 function accept(list){const a=Array.from(list||[]);setFiles(a);setResult(null);setBatch([]);setError("");setNotice(a.length?`${a.length} evidence item${a.length>1?"s":""} queued.`:"")}
 async function scan(){if(!files.length)return;setLoading(true);setProgress(0);setError("");setNotice("");setResult(null);setBatch([]);try{const out=[];for(let i=0;i<files.length;i++){const f=new FormData();f.append("file",files[i]);out.push(await request("/api/integrity/scan",{method:"POST",body:f}));setProgress(Math.round(((i+1)/files.length)*100))}setBatch(out);setResult(out[0]);await load();setNotice(`${out.length} evidence item${out.length>1?"s":""} analyzed successfully.`)}catch(e){setError(e.message)}finally{setLoading(false)}}
 async function inspectUrl(){setError("");setNotice("");setResult(null);try{const u=new URL(url.trim());if(!/^https?:$/.test(u.protocol))throw new Error("Only HTTP and HTTPS links are supported.");const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(u.href));const h=[...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,"0")).join("");setResult({filename:u.hostname,status:"URL REGISTERED",sha256:h,size_bytes:u.href.length,analysis:{verdict:"URL accepted for provenance tracking",risk:{risk_score:0,risk_level:"PENDING",recommended_action:"REVIEW",confidence:0,risk_factors:["Remote content was not fetched or executed by the browser."]}}});setNotice("URL format verified and fingerprinted locally. Remote-content scanning requires a server-side URL ingestion endpoint.")}catch(e){setError(e.message||"Enter a valid URL.")}}
 return <div className={`app ${risky?"danger-state":""}`}><div className="grid"/><header className="top"><a className="brand" href="#top"><span className="mark"><Icon t="shield"/></span><span><strong>CV<span>SHIELD</span></strong><small>COMPUTER VISION ASSURANCE</small></span></a><nav>{[["scanner","Scanner"],["evidence","Evidence"],["audit","Audit"]].map(([k,l])=><button key={k} className={tab===k?"active":""} onClick={()=>setTab(k)}>{l}</button>)}</nav><div className="service"><i className={health?"on":""}/> {health?"PROTECTED":"CONNECTING"}</div></header>
 <main id="top"><section className="hero"><div><div className="kicker">/ TRUSTED EVIDENCE WORKSPACE</div><h1>{result?(risky?"Review required":"Integrity check complete"):"Evidence assurance, without the guesswork."}</h1><p>Validate contributed computer-vision evidence with cryptographic fingerprints, explainable risk signals and a tamper-evident audit trail.</p><div className="chips"><span>SHA-256</span><span>NON-EXECUTING</span><span>AUDITABLE</span><span>MODEL-AGNOSTIC</span></div></div><div className={`orb-card ${risky?"bad":result?"good":""}`}><div className="orb-top"><span>ASSURANCE STATUS</span><b>{result?(risky?"REVIEW":"VERIFIED"):"READY"}</b></div><div className="orb"><span>{result?(risky?"!":"✓"):"—"}</span></div><strong>{result?(risky?"Suspicious signal detected":"Evidence assessed"):"Awaiting evidence"}</strong><small>{result?`${risk.score}/100 risk · ${risk.action}`:"Choose an input source below"}</small></div></section>
 {tab==="scanner"&&<><section className="workspace"><div className="panel"><div className="head"><div><small>01 / INGESTION</small><h2>Evidence Scanner</h2></div><em>● SECURE MODE</em></div><div className="modes">{[["image","Image","Images & frames"],["video","Video","Video evidence"],["file","File","Models & datasets"],["folder","Folder","Batch evidence"],["link","Link","URL provenance"]].map(([k,l,s])=><button className={mode===k?"sel":""} key={k} onClick={()=>selectMode(k)}><Icon t={k}/><span><b>{l}</b><small>{s}</small></span></button>)}</div>{mode==="link"?<div className="linkbox"><small>REMOTE EVIDENCE URL</small><div className="url"><span>https://</span><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="example.com/evidence"/><button onClick={inspectUrl}>CHECK LINK <Icon t="arrow"/></button></div><p>Only the URL string is fingerprinted locally. Remote content is not downloaded or executed.</p></div>:<><input ref={input} className="hide" type="file" multiple={mode==="folder"} webkitdirectory={mode==="folder"?"true":undefined} accept={mode==="image"?"image/*":mode==="video"?"video/*":undefined} onChange={e=>accept(e.target.files)}/><div className={`drop ${files.length?"has":""}`} onClick={()=>input.current?.click()} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();accept(e.dataTransfer.files)}}><div className="dropmark"><Icon t={mode}/></div><b>{files.length?`${files.length} item${files.length>1?"s":""} ready`:`Drop ${mode==="folder"?"a folder":mode+" evidence"} here`}</b><span>{files.length?files.slice(0,2).map(f=>f.name).join(" · ")+(files.length>2?` · +${files.length-2} more`:""):"or click to browse your device"}</span><small>{mode==="image"?"PNG · JPG · WEBP · TIFF":mode==="video"?"MP4 · MOV · WEBM · AVI":mode==="folder"?"Complete evidence folder":"Any supported evidence artifact"}</small></div>{files.length>0&&<div className="queue">{files.slice(0,6).map((f,i)=><div key={i}><b>{f.name}</b><span>{bytes(f.size)}</span></div>)}{files.length>6&&<small>+ {files.length-6} more queued</small>}</div>}<button className="scan" disabled={!files.length||loading} onClick={scan}>{loading?<><i className="spinner"/> ANALYZING {progress}%</>:<>RUN INTEGRITY CHECK <Icon t="arrow"/></>}</button></>}{(error||notice)&&<div className={`msg ${error?"err":"ok"}`}><b>{error?"!":"✓"}</b>{error||notice}</div>}</div>
 <aside className="panel monitor"><div className="head"><div><small>02 / DECISION ENGINE</small><h2>Risk Monitor</h2></div><i className={`pulse ${risky?"red":""}`}/></div><div className="risk"><div className="ring" style={{"--a":`${risk.score*3.6}deg`}}><strong>{risk.score}</strong><small>/100</small></div><div><small>CURRENT ASSESSMENT</small><b>{risk.level}</b><span>{risk.action==="—"?"Awaiting analysis":`Recommended action: ${risk.action}`}</span></div></div><div className="signals">{[["Data integrity",result?"ASSESSED":"WAITING"],["Model integrity",result?"READY":"WAITING"],["Inference binding",result?"BINDABLE":"WAITING"],["Audit trail",audit?.chain_valid===false?"CHECK":"VALID"]].map(([a,b])=><div key={a}><span>{a}</span><b>{b}</b></div>)}</div><div className="factors"><small>OBSERVED SIGNALS · BACKEND EVIDENCE</small>{risk.factors.length?risk.factors.map((f,i)=><p key={i}>• {f}</p>):<p>• No active findings</p>}</div></aside></section>{result&&<section className={`result ${risky?"danger":""}`}><div className="head"><div><small>03 / VERIFICATION OUTPUT</small><h2>Evidence Result</h2></div><b>{risky?"⚠ REVIEW":"✓ VERIFIED"}</b></div><div className="resultgrid"><div><small>SHA-256 FINGERPRINT</small><code>{result.sha256||"Not returned"}</code><div className="stats"><span>NAME<b>{result.filename||"—"}</b></span><span>STATUS<b>{result.status||"—"}</b></span><span>SIZE<b>{bytes(result.size_bytes)}</b></span><span>CONFIDENCE<b>{Math.round(risk.confidence*100)}%</b></span></div></div><div className="verdict"><small>VERDICT</small><b>{result.analysis?.verdict||"Assessment completed"}</b>{batch.length>1&&<span>{batch.length} evidence items processed.</span>}</div></div></section>}</>}
 {tab==="evidence"&&<section className="panel page"><div className="head"><div><small>03 / REGISTRY</small><h2>Evidence Inventory</h2></div><button className="ghost" onClick={load}>↻ Refresh</button></div><div className="empty"><Icon t="file"/><b>Evidence registry connected</b><span>{audit?.events?.length??0} audit events available.</span></div></section>}
 {tab==="audit"&&<section className="panel page"><div className="head"><div><small>04 / FORENSICS</small><h2>Audit Integrity</h2></div><em>{audit?.chain_valid===false?"CHAIN CHECK REQUIRED":"CHAIN VALID"}</em></div><div className="audit"><strong>{audit?.chain_valid===false?"!":"✓"}</strong><div><b>{audit?.chain_valid===false?"Audit chain needs review":"Tamper-evident audit chain is valid"}</b><span>{audit?.events?.length??0} events observed by the assurance service.</span></div></div></section>}</main><footer><span><b>CVSHIELD</b> · EVIDENCE-FIRST ASSURANCE</span><span>NON-EXECUTING · CRYPTOGRAPHIC PROVENANCE</span><span>BUILD 2.0</span></footer></div>}
ReactDOM.createRoot(document.getElementById("root")).render(<React.StrictMode><App/></React.StrictMode>);
